VERSION := 1.5.9

CXX ?= g++
EXE ?= bread_engine_$(VERSION)

CXXFLAGS ?= -std=c++20 -O3 -mavx2 -march=native
INCLUDES := -Isrc -Isrc/extern -Isrc/extern/Fathom/src
DEFS := \
	-Dbread_VERSION=\"$(VERSION)\" \
	-Dbread_NNUE_MODEL_PATH=\"neural_networks/model_NNUE_2-40960_2x256_32_32_1_quant_layers\" \
	-Dbread_DEBUG_UCI_COMMANDS_PATH=\"utils/commands.txt\"

SRC := \
	src/nonsense.cpp \
	src/misc.cpp \
	src/sorted_move_gen.cpp \
	src/nnue/nnue.cpp \
	src/nnue/nnue_board.cpp \
	src/transposition_table.cpp \
	src/core.cpp \
	src/benchmark.cpp \
	src/extern/Fathom/src/tbprobe.cpp \
	src/uci.cpp \
	src/run_uci.cpp

OBJ := $(SRC:.cpp=.o)

all: $(EXE)

$(EXE): $(OBJ)
	$(CXX) $(CXXFLAGS) $(OBJ) -o $@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(DEFS) -c $< -o $@

# disable warnings generated by fathom
src/extern/Fathom/src/tbprobe.o: CXXFLAGS += -w

.PHONY: clean
clean:
	rm -f $(OBJ) $(EXE)
